# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeconv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-conv
  template:
    metadata:
      labels:
        app: kube-conv
    spec:
      containers:
        - name: kube-conv
          image: lschulmeister/conversao-temperatura:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-web
spec:
  selector:
    app: kube-conv
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30000
  type: NodePort