TRUNCATE customers RESTART IDENTITY CASCADE;
TRUNCATE employees RESTART IDENTITY CASCADE;
TRUNCATE orders RESTART IDENTITY CASCADE;
TRUNCATE orders_details RESTART IDENTITY CASCADE;
TRUNCATE payment RESTART IDENTITY CASCADE;
TRUNCATE product RESTART IDENTITY CASCADE;
TRUNCATE product_details RESTART IDENTITY CASCADE;